Que1=input("How are you doing today?\n")
good1="Really Good"
good2="Perfect"
good3="Good"
good4="Tres Bien"
good5="Bien"
soso1="meh"
soso2="eh"
soso3="could be better, could be worse"
bad1=
bad2=
bad3=
bad4=
bad5=
misc1=">w<"
misc2="bored"
misc3=
misc4=
misc5=
